#!/usr/bin/env bash
# vi: set syntax=sh ts=4 sw=4 sts=4 et ff=unix ai si :
#
# convert-audio-files - takes in various music file types and converts
#                       them to MP3 with tags and artwork
#
# (c) Steven Scholnick <scholnicks@gmail.com>
# The convert-audio-files source code is published under a MIT license.

tagOnly="false"
if [[ "$1" = "--tag" ]]; then
    tagOnly="true"
    shift
fi

[[ "$#" -ne 4 ]] && echo "Usage: convert-audio-files setlist artist album artwork" && exit 1

# Initial cleanup
rm -f *.md5 *.ffp *.jpg *.JPG *.txt *.pdf *.jpeg *.log

# Create .wav files
if [[ "$tagOnly" == "false" ]]; then
    echo "Creating WAV files"
fi

# Convert non-wav files to .wav
# Support: Flac, Ogg, AIFF, M4A, MP3, Shorten

# opus
for i in *.opus; do ffmpeg -loglevel 0 -nostats -i "$i" "${i%.*}.wav"; done
rm -f *.opus

# shorten
for i in *.shn; do ffmpeg -loglevel 0 -nostats -i "$i" "${i%.*}.wav"; done
rm -f *.shn

# flac
flac --silent --delete-input-file -d *.flac 1>/dev/null 2>&1

# aiff
chname substitute --quiet .aif .aiff *.aif 1>/dev/null 2>&1
for i in *.aiff; do sox --no-show-progress "$i" "${i%.*}.wav" 1>/dev/null 2>&1; done
rm -f *.aiff

# m4a
for i in *.m4a; do ffmpeg -loglevel 0 -nostats -i "$i" "${i%.*}.wav"; done
rm -f *.m4a

if [[ "$tagOnly" == "false" ]]; then
    # if the input files are MP3s, convert them to wav
    for i in *.mp3; do sox --no-show-progress "$i" "${i%.*}.wav" 1>/dev/null 2>&1; done
    rm -f *.mp3

    # now have all .wav files, fix the names and convert them to mp3

    # Give the full filenames with number prefixes
    chname titles $1 *.wav || exit -1

    # Create the final mp3 files from the .wav files
    for i in *.wav
    do
        echo "Converting $i"
        lame --nohist --silent "$i" "${i%.*}.mp3" || exit -1
    done
    rm -f *.wav
fi

echo
echo "Adding mp3 tags and artwork"

# convert webp to jpg

if [[ "${4: -5}" == ".webp" ]]; then
    jpgFile=${4%.webp}.jpg
    gm convert $4 ${jpgFile}
    artwork=$jpgFile
else
    artwork="$4"
fi

# Optimize the jpg
optimized_artwork="$(mktemp).jpg"
jpegtran -copy none -optimize -outfile $optimized_artwork "$artwork" || exit -1

# Add the MP3 tags

total=$(/bin/ls -1q *.mp3 | wc -l)
counter=1
for f in *.mp3; do
    song="${f:5}"
    eyed3 --quiet \
        --title "${song%.mp3}" \
        --album "$3" \
        --artist "$2" \
        --album-artist "$2" \
        --disc-num 0 \
        --track "$counter" \
        --release-date "${3##*.}" \
        --recording-date "${3##*.}" \
        --add-image "$optimized_artwork:FRONT_COVER:Album Artwork" \
        --track-total "$total" \
        "$f" 1>/dev/null
    ((counter++))
done

# Cleanups

chmod 600 *.mp3
rm -f $optimized_artwork .DS_Store

exit 0

